---
title: "Mapping"
author: "Thi Phuong Huynh"
date: "1/17/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

rm(list=ls())
#Tom's codes##############################
library(sf) # for reading shape files into R
library(tmap)#for creating the map
library(dplyr)
library(tidyveCrse)
```

#data input
```{r data input}
#NUTS_3##############################
nuts3shapefile <- read_sf("C:/Users/huynh/sciebo/NRW_descriptive/data/NUTS_RG_20M_2021_3035.shp") # for the attached map you need to download the specific shape files from Eurostat. I used NUTS3
nuts3shapefile <- nuts3shapefile %>% filter(CNTR_CODE == "DE") # chose only Germany
# nuts3shapefile <- nuts3shapefile %>% filter(LEVL_CODE==3 ) # chose only NRW
#COVID-19###########################
covid_data <- read.csv("C:/Users/huynh/sciebo/NRW_descriptive/data/case_county_waves.csv")
covid_data <- covid_data %>% select("NUTS_ID", "cases_wave4")
covid_data$incper100000<- covid_data$cases_wave4/NRW_pop*100000


```

#demographic data
```{r demographic data}
#pop######################
NRW_pop <- 17925570
NRW_under12 <- 2014762
NRW_vacc <- NRW_pop -NRW_under12
start_day <- as.Date("2020-02-27")# data before this day won't be counted

```


```{r}

#NUTS_3##############################
nuts3shapefile <- read_sf("C:/Users/huynh/sciebo/NRW_descriptive/data/NUTS_RG_20M_2021_3035.shp") # for the attached map you need to download the specific shape files from Eurostat. I used NUTS3
nuts3shapefile <- nuts3shapefile %>% filter(CNTR_CODE == "DE") # chose only Germany
# nuts3shapefile <- nuts3shapefile %>% filter(LEVL_CODE==3 ) # chose only NRW
#COVID-19###########################
covid_data <- read.csv("C:/Users/huynh/sciebo/NRW_descriptive/data/case_county_waves.csv")
covid_data <- covid_data %>% select("NUTS_ID", "cases_wave4")
covid_data$incper100000<- covid_data$cases_wave4/NRW_pop*100000

#division 2
covid_data$incper100000_grouped <- cut(covid_data$incper100000, breaks=c(-Inf,25,50,75,100,125,150,175, 200,Inf))
covid_data$incper100000_grouped <- factor(covid_data$incper100000_grouped, levels=c("(-Inf,25]", "(25,50]", "(50,75]", "(75,100]", "(100,125]", "(125,150]",
                                                                           "(150,175]", "(175,200]", "(200, Inf]"),
                                       labels=c("0-25",">25-50",">50-75", ">75-100", ">100-125", ">125-150", ">150-175", ">175-200",
                                                 ">200"), ordered=T)

nuts3shapefile <- filter(nuts3shapefile,nuts3shapefile$NUTS_ID %in% covid_data$NUTS_ID)

nuts3shapefile1 <- merge(nuts3shapefile,covid_data, by = "NUTS_ID")

# nrw_nuts <- merge(x=nuts3shapefile , y=covid_data,
#                   by.x= "NUTS_ID",
#                   by.y= "NUTS_NAME",
#                   all.x=F, all.y=T) # match shape data with covid data

# nrw_nuts <- merge(nuts3shapefile , y=covid_data,
#                   by.x= "NUTS_ID",
#                   by.y= "NUTS3",
#                   all.x=F, all.y=T) # match shape data with covid data
legend_label=c("0-25",">25-50",">50-75", ">75-100", ">100-125", ">125-150", ">150-175", ">175-200",
               ">200")

mapNRW <- tm_shape(nuts3shapefile1) +
  tm_fill("incper100000_grouped", palette = "Blues", legend.show = F) +
  tm_borders("black") + tm_add_legend(title = "Incidence", labels = legend_label, col = RColorBrewer::brewer.pal(9, "Blues")) +
  # \n : line down
  tm_layout(title = "COVID-19 infection_W4 \n ( per 100,000)", title.fontfamily = "sans", title.size = 2.0,
            title.fontface= "bold", title.position= c(0.01,0.9),frame=F,
            legend.outside = F, legend.frame = F,
            legend.position = c(0.9,0.0), legend.width = 1,
            legend.title.size = 2.0, legend.text.size= 1.5,
            legend.title.fontfamily ="sans",legend.title.fontface ="bold")
mapNRW

```


```{r}
#Online tutorial#########################
#https://cran.r-project.org/web/packages/tmap/vignettes/tmap-getstarted.html
##Hello World!#####################
library(tmap)
data("World")

tm_shape(World) +
  tm_polygons("HPI")
##Interactive maps################
tmap_mode("view")

tm_shape(World) +
  tm_polygons("HPI")
##Multiple shapes and layers####
#A shape is a spatial object (with a class from sf, sp, stars, or raster).
#Multiple shapes and also multiple layers per shape can be plotted:
data(World, metro, rivers, land)

tmap_mode("plot")
## tmap mode set to plotting
tm_shape(land) +
  tm_raster("elevation", palette = terrain.colors(10)) +
  tm_shape(World) +
  tm_borders("white", lwd = .5) +
  tm_text("iso_a3", size = "AREA") +
  tm_shape(metro) +
  tm_symbols(col = "red", size = "pop2020", scale = .5) +
  tm_legend(show = FALSE)
##Facets###################
###1.assigning multiple variable names to one aesthetic###################
tmap_mode("view")
tm_shape(World) +
  tm_polygons(c("HPI", "economy")) +
  tm_facets(sync = TRUE, ncol = 2)
###2.splitting the spatial data with the by argument of tm_facets#########
tmap_mode("plot")
##tmap mode set to plotting

data(NLD_muni)

NLD_muni$perc_men <- NLD_muni$pop_men / NLD_muni$population * 100

tm_shape(NLD_muni) +
  tm_polygons("perc_men", palette = "RdYlBu") +
  tm_facets(by = "province")

###3.using the tmap_arrange function######
tmap_mode("plot")
## tmap mode set to plotting

data(NLD_muni)
tm1 <- tm_shape(NLD_muni) + tm_polygons("population", convert2density = TRUE)
tm2 <- tm_shape(NLD_muni) + tm_bubbles(size = "population")

tmap_arrange(tm1, tm2)
## Legend labels were too wide. Therefore, legend.text.size has been set to 0.27. Increase legend.width (argument of tm_layout) to make the legend wider and therefore the labels larger.
## The legend is too narrow to place all symbol sizes.
##Basemaps and overlay tile maps######
```

